---
minikube_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'

minikube_arch: "{{ minikube_arch_map[ansible_architecture] | default(ansible_architecture) }}"
minikube_platform: '{{ minikube_os }}-{{ minikube_arch }}'
minikube_file: "minikube-{{ minikube_platform }}"
minikube_url: '{{ minikube_mirror }}/{{ minikube_version }}/{{ minikube_file }}'
minikube_checksum: '{{ minikube_checksums[minikube_version][minikube_platform] }}'
minikube_install_target: '{{ minikube_install_dir }}/{{ minikube_file }}-{{ minikube_version }}'
minikube_install_link: '{{ minikube_install_dir }}/minikube'
