---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name:
          - "conntrack"  # Kubernetes 1.23.3 requires conntrack to be installed in root's path
          - "iproute"  # minikube dependency
          - "ethtool"  # minikube dependency
          - "socat"  # minikube dependency
        state: present
      when:
        - ansible_distribution in [ "RedHat", "CentOS", "Amazon", "Rocky", "AlmaLinux", "Fedora" ]

    - name: Install dependencies
      ansible.builtin.package:
        name:
          - "conntrack"  # Kubernetes 1.23.3 requires conntrack to be installed in root's path
          - "iproute2"  # minikube dependency
          - "ethtool"  # minikube dependency
          - "socat"  # minikube dependency
        state: present
      when:
        - ansible_os_family == "Debian"

# Possible driver for local installation
#   roles:
#     - role: mullholland.docker
