---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Test minikube binary
      ansible.builtin.command: '/usr/bin/minikube-linux-amd64-v1.25.2 version'
      register: minikube_version
      changed_when: minikube_version.rc != 0

    - name: Test minikube binary system link
      ansible.builtin.command: '/usr/bin/minikube version'
      register: minikube_link_version
      changed_when: minikube_link_version.rc != 0
